
%YAML 1.2
---
---
# Default settings, where all machines use mockup connection
# Copy this into your /etc/hosts file for convenience
# C-BS 192.168.2.27
# C-RS1 192.168.2.23
# C-RS2 192.168.2.26
# C-CS2 192.168.2.25
#
# M-BS 192.168.2.33
# M-RS1 192.168.2.31
# M-RS2 192.168.2.34
# M-CS2 192.168.2.33


llsfrb:
  mps:
    enable: true
    stations:
      C-BS:
        active: true
        type: BS
        host: 192.168.2.27
        port: !tcp-port 4840
        connection: mockup
      C-CS1:
        active: true
        host: 192.168.2.24
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-CS2:
        active: true
        host: 192.168.2.25
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-RS1:
        active: true
        host: 192.168.2.23
        port: !tcp-port 4840
        type: RS
        connection: mockup
      C-RS2:
        active: true
        host: 192.168.2.26
        port: !tcp-port 4840
        type: RS
        connection: mockup
      C-DS:
        active: true
        host: 192.168.2.28
        port: !tcp-port 4840
        type: DS
        connection: mockup
      C-SS:
        active: true
        host: 192.168.2.35
        port: !tcp-port 4840
        type: SS
        connection: mockup
      M-BS:
        active: true
        host: 192.168.2.33
        port: !tcp-port 4840
        type: BS
        connection: mockup
      M-CS1:
        active: true
        host: 192.168.2.30
        port: !tcp-port 4840
        type: CS
        connection: mockup
      M-CS2:
        active: true
        host: 192.168.2.32
        port: !tcp-port 4840
        type: CS
        connection: mockup
      M-RS1:
        active: true
        host: 192.168.2.31
        port: !tcp-port 4840
        type: RS
        connection: mockup
      M-RS2:
        active: true
        host: 192.168.2.34
        port: !tcp-port 4840
        type: RS
        connection: mockup
      M-DS:
        active: true
        host: 192.168.2.29
        port: !tcp-port 4840
        type: DS
        connection: mockup
      M-SS:
        active: true
        host: 192.168.2.22
        port: !tcp-port 4840
        type: SS
        connection: mockup
