%YAML 1.2
---
---
# Default communication settings.

llsfrb:
  comm:
    protobuf-dirs: ["@SHAREDIR@/msgs/rcll-protobuf-msgs"]
    # The rebroadcaster allows to forward all messages between the configured
    # peers.
    # This is mainly useful to avoid port binding collisions when multiple
    # peers should talk to the refbox on a local machine.
    # The configuration is used by the rcll-proto-rebroadcaster tool and is
    # ignored by the refbox
    rebroadcaster:
      package-loss: 0.0
      # all peers which need the comm plugin
      # write down as follows:
      # adrresses:  ["address_1", "address_2", ...]
      # send-ports: [send_port_1, send_port_2, ...]
      # revc-ports: [recv_port_1, recv_port_2, ...]
      addresses: ["127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1",
                  "127.0.0.1", "127.0.0.1", "127.0.0.1", "127.0.0.1"]
      send-ports: [4445, 4411, 4412, 4413, 4414, 4415, 4416, 4418]
      recv-ports: [4444, 4421, 4422, 4423, 4424, 4425, 4426, 4428]
      use-crypto1: true
      send-ports-crypto1: [4446, 4451, 4452, 4453, 4454, 4455, 4456, 4458]
      recv-ports-crypto1: [4441, 4471, 4472, 4473, 4474, 4475, 4476, 4478]
      use-crypto2: true
      send-ports-crypto2: [4447, 4461, 4462, 4463, 4464, 4465, 4466, 4468]
      recv-ports-crypto2: [4442, 4481, 4482, 4483, 4484, 4485, 4486, 4488]
