version: '3.7'
services:
  mongodb:
    container_name: "mongodb"
    network_mode: "host"
    image: ${MONGODB_IMAGE}:${MONGODB_TAG}
    restart: "no"
    command: mongod --port ${RC_MONGODB_PORT}
    volumes:
      - '${RC_MONGODB_DATA_DIR}:/data/db:z'
