version: "3"
services:
  broker:
    image: ${MQTT_BROKER_IMAGE}:${MQTT_BROKER_TAG}
    network_mode: host
    volumes:
      - ${MQTT_BROKER_CONFIG}/conf:/mosquitto/config:z
      - ${MQTT_BROKER_CONFIG}/data:/mosquitto/data:z
      - ${MQTT_BROKER_CONFIG}/log:/mosquitto/log:z
