version: '3.7'
services:
  mongodb-check:
    container_name: mongodb-check
    image: ${MONGODB_IMAGE}:${MONGODB_TAG}
    command: ["sh", "-c", "mongosh ${RC_MONGODB_URI} --eval 'printjson(db.serverStatus())' || (sleep 1; exit -1)"]
    network_mode: "host"
    restart: on-failure:10

  refbox:
    container_name: refbox
    image: "${REFBOX_IMAGE}:${REFBOX_TAG}"
    network_mode: "host"
    depends_on:
      mongodb-check:
        condition: service_completed_successfully
    restart: "on-failure"
    command: llsf-refbox ${REFBOX_ARGS}
    volumes:
      - ${REFBOX_CONFIG}:/etc/rcll-refbox/:z
      - ${REFBOX_LOGS_DIR}/refbox:/logs:z

  frontend:
    container_name: refbox-frontend
    image: "${REFBOX_FRONTEND_IMAGE}:${REFBOX_FRONTEND_TAG}"
    ports:
      - 8080:80
    restart: "no"
