version: '3.7'
services:
  refbox:
    image: "${REFBOX_IMAGE}:${REFBOX_TAG}"
    network_mode: "host"
    depends_on:
      - mongodb
    restart: "always"
    command: llsf-refbox --dump-cfg
    volumes:
      - ${REFBOX_CONFIG_GAME}:/etc/rcll-refbox/game/default_game.yaml
      - ${REFBOX_CONFIG_SIMULATION}:/etc/rcll-refbox/simulation/default_simulation.yaml
      - ${REFBOX_CONFIG_COMM}:/etc/rcll-refbox/comm/default_comm.yaml
      - ${REFBOX_CONFIG_MPS}:/etc/rcll-refbox/mps/default_mps.yaml
      - ${REFBOX_CONFIG_TEAM}:/etc/rcll-refbox/team/default_team.yaml
      - ${REFBOX_CONFIG_CHALLENGE}:/etc/rcll-refbox/challenges/default_challenges.yaml
      - ${REFBOX_CONFIG_MONGODB}:/etc/rcll-refbox/mongodb/default_mongodb.yaml

  frontend:
    image: "${REFBOX_FRONTEND_IMAGE}:${REFBOX_FRONTEND_TAG}"
    network_mode: "host"
    restart: "always"
  mongodb:
    container_name: "mongodb"
    network_mode: "host"
    image: mongo
    restart: "always"
    volumes:
      - './data:/data/db'
