%YAML 1.2
---
---
# Start a fresh game per default.

llsfrb:
  game:
    teams: [Carologistics, GRIPS, Solidus, Babytigers-R]
    crypto-keys:
      Carologistics: randomkey
      GRIPS: randomkey
      Solidus: randomkey
      Babytigers-R: randomkey
